
@port = 3006
### Token for Testy McTesty
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjYwODFjYWI3ODU0NDczMWZmMDkxM2RjNiIsImlhdCI6MTYxOTEyMTQzOH0.EBZoMBJj2wJLAhky4rKiqXwbHqr6LWxIrSo6z_9EHtM
###
POST http://localhost:{{port}}/api/login
content-type: application/json

{
    "username": "Test", 
    "password": "super secret!"
}
###
GET http://localhost:{{port}}/api/blogs
Authorization: bearer {{token}}
###
POST http://localhost:{{port}}/api/blogs
content-type: application/json
Authorization: bearer {{token}}

{
    "title": "Blog on testing", 
    "author": "Me me",
    "url": "www.me.com",
    "likes": 5
}
###
POST http://localhost:{{port}}/api/blogs
content-type: application/json

{
    "title": "Second test blog", 
    "author": "You yu",
    "url": "www.bloggerhost.com",
    "likes": 400
}
###
POST http://localhost:{{port}}/api/blogs
content-type: application/json

{
    "title": "Test invalid fields", 
    "author": 500,
    "url": 200,
    "likes": "invalid value"
}
###
GET http://localhost:{{port}}/api/users
###
POST http://localhost:{{port}}/api/users
content-type: application/json

{
    "username": "Test", 
    "name": "Testy McTesty",
    "password": "super secret!"
}